import Head from 'next/head'
import { Box, Typography, Paper, TextField, Button } from '@mui/material'

export default function Home() {
  return (
    <Box>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box sx={{display: 'flex', height: '100vh', flexDirection: 'column', justifyContent: 'center', alignItems: 'center', textAlign: 'center', px: 20, py: 10, bgcolor: 'rgb(244, 227, 255)'}}>
        <Paper sx={{display: 'flex', height: '100%', flexDirection: 'column', justifyContent: 'center', alignItems: 'center', textAlign: 'center', px: 20, borderRadius: 10}} elevation={6}>
          <Typography variant="h2" color="danger">Hi, I&apos;m <b>Muskan Vaswan</b></Typography>
          <Typography variant="body1" color="danger">I&apos;m interested in knowing what you have to say. You can leave here any opinions you have of me, anything you need me to know or even just your musings of life in general, using your blockchain wallet!</Typography>
          <Box sx={{display: 'flex', m: 3}}>
            <TextField variant="outlined" sx={{mr: 1}}/>
            <Button variant="contained" sx={{bgcolor: 'rgb(244, 227, 255)', color: 'black', '&:hover': {bgcolor: "#fff"},}}>Submit</Button>
          </Box>
        </Paper>
      </Box>
    </Box>
  )
}
