import Head from 'next/head'
import { useEffect, useState } from 'react'
import { Box, Typography, Paper, TextField, Button, IconButton, LinearProgress } from '@mui/material'
import DoneIcon from '@mui/icons-material/Done';

export default function Home() {
  const [ currentAccount, setCurrentAccount ] = useState("")

  const checkIfWalletIsConnected = async () => {
    try {
      const { ethereum } = window;

      if (!ethereum) {
        console.log("Make sure you have metamask!");
        return;
      } else {
        console.log("We have the ethereum object", ethereum);
      }
      const accounts = await ethereum.request({ method: "eth_accounts" });

      if (accounts.length !== 0) {
        const account = accounts[0];
        console.log("Found an authorized account:", account);
        setCurrentAccount(account)
      } else {
        console.log("No authorized account found")
      }
    } catch (error) {
      console.log(error);
    }
  }

  const connectWallet = async () => {
    try {
      const { ethereum } = window;

      if (!ethereum) {
        alert("Get MetaMask!");
        return;
      }

      const accounts = await ethereum.request({ method: "eth_requestAccounts" });

      console.log("Connected", accounts[0]);
      setCurrentAccount(accounts[0]);
    } catch (error) {
      console.log(error)
    }
  }

  useEffect(() => {
    checkIfWalletIsConnected();
  }, [])

  return (
    <Box>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box sx={{display: 'flex', height: '100vh', flexDirection: 'column', justifyContent: 'center', alignItems: 'center', textAlign: 'center', px: 20, py: 10, bgcolor: 'rgb(0, 8, 108)', background: 'linear-gradient( 65.9deg,  rgba(85,228,224,1) 5.5%, rgba(75,68,224,0.74) 54.2%, rgba(64,198,238,1) 55.2%, rgba(177,36,224,1) 98.4% );'}}>
        <Paper sx={{display: 'flex', height: '100%', flexDirection: 'column', justifyContent: 'center', alignItems: 'center', textAlign: 'center', px: 20, borderRadius: 10, bgcolor: 'rgba(250, 250, 250, 0)'}} elevation={0}>
          <Typography variant="h2" color="danger">Hi, I&apos;m <strong>Muskan Vaswan</strong></Typography>
          <Typography variant="body1" color="danger">I&apos;m interested in knowing what you have to say. You can leave here any opinions you have of me, anything you need me to know or even just your musings of life in general, using your blockchain wallet!</Typography>
          {currentAccount !== "" ?
          <Box sx={{display: 'flex', mt: 3, width: 300}}>
            <Paper sx={{mx: 1, width: '100%', px: 1, pt: 1, borderRadius: '10px', bgcolor: 'rgba(255, 255, 255, 0)', position: 'relative'}} elevation={6}>
              <Box sx={{width: '100%', display: 'flex', justifyContent: 'space-between', mb: 1}}>
                <TextField
                  variant="standard"
                  sx={{width: '85%', p:0, bgcolor: 'rgba(0, 0, 0, 0)', borderRadius: '10px', '& input': {fontSize: 15}}}
                />
                <IconButton size="small" sx={{bgcolor: 'black', color: 'white', borderRadius: 2}}><DoneIcon size="small"/></IconButton>
              </Box>
              {false && <LinearProgress/>}
            </Paper>
          </Box>
        :
        <Box sx={{mt: 3}}>
          <Button
            variant="contained"
            size="large"
            sx={{bgcolor: "black", color: "white", mt: 3, borderRadius: 5}}
            onClick={connectWallet}>
            Connect Wallet
          </Button>
        </Box>}
        </Paper>
      </Box>
    </Box>
  )
}
